version: "3"
services:
  frontend-blue:
    image: ${DOCKER_USERNAME}/dong-gle-frontend-${INFRA_PROFILE}

  backend-blue:
    image: ${DOCKER_USERNAME}/dong-gle-backend-${INFRA_PROFILE}
    volumes:
      - /home/ubuntu/logs/:/logs/
    environment:
      - HIKARI_MAX_POOL_SIZE
      - HIKARI_MIN_IDLE
      - TOMCAT_MAX_THREADS
      - TOMCAT_ACCEPT_COUNT
      - TOMCAT_MAX_CONNECTIONS
      - SPRING_PROFILES_ACTIVE
networks:
  default:
    name: donggle-network
    external: true
