version: "3"
services:
  frontend-green:
    image: ${DOCKER_USERNAME}/dong-gle-frontend-${INFRA_PROFILE}

  backend-green:
    image: ${DOCKER_USERNAME}/dong-gle-backend-${INFRA_PROFILE}
    volumes:
      - /home/ubuntu/logs/:/logs/
      - /home/ubuntu/javaagent/:/javaagent/
    environment:
      - HIKARI_MAX_POOL_SIZE
      - HIKARI_MIN_IDLE
      - TOMCAT_MAX_THREADS
      - TOMCAT_ACCEPT_COUNT
      - TOMCAT_MAX_CONNECTIONS
      - SPRING_PROFILES_ACTIVE
      - DD_ENV=dev
      - DD_SERVICE=Backend
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_AGENT_PORT=8126
      - DD_LOGS_INJECTION=true
networks:
  default:
    name: donggle-network
    external: true
