version: "3"
services:
  frontend-blue:
    image: ${DOCKER_USERNAME}/dong-gle-frontend-${INFRA_PROFILE}

  backend-blue:
    image: ${DOCKER_USERNAME}/dong-gle-backend-${INFRA_PROFILE}
    volumes:
      - /home/ubuntu/logs/:/logs/
    environment:
      - SPRING_PROFILES_ACTIVE
networks:
  default:
    name: donggle-network
    external: true
