version: "3"
services:
  frontend:
    image: ${DOCKER_USERNAME}/dong-gle-frontend-${INFRA_PROFILE}
    expose:
      - 3000

  backend:
    image: ${DOCKER_USERNAME}/dong-gle-backend
    expose:
      - 8080
    volumes:
      - /home/ubuntu/logs/:/logs/
    environment:
      - SPRING_PROFILES_ACTIVE

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
      - /home/ubuntu/certs/:/etc/nginx/certs/
      - ./conf-${INFRA_PROFILE}/:/etc/nginx/conf.d/
      - /home/ubuntu/nginx-logs/:/var/log/nginx/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend
