version: "3"
services:
  frontend:
    image: ${DOCKER_USERNAME}/dong-gle-frontend-${PROFILE}
    expose:
      - 3000

  backend:
    image: ${DOCKER_USERNAME}/dong-gle-backend
    expose:
      - 8080
    volumes:
      - /home/ubuntu/logs/:/logs/
    environment:
      - SPRING_PROFILES_ACTIVE
      - DB_URL
      - DB_USERNAME
      - DB_PASSWORD
      - KAKAO_CLIENT_ID
      - KAKAO_CLIENT_SECRET
      - TISTORY_CLIENT_ID
      - TISTORY_CLIENT_SECRET
      - NOTION_CLIENT_ID
      - NOTION_CLIENT_SECRET
      - JWT_SECRET_KEY
      - ACCESS_TOKEN_EXPIRE_LENGTH
      - REFRESH_TOKEN_EXPIRE_LENGTH

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
      - /home/ubuntu/certs/:/etc/nginx/certs/
      - ./conf-${PROFILE}/:/etc/nginx/conf.d/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend
