version: "3"
services:
  frontend:
    image: ${DOCKER_USERNAME}/dong-gle-frontend
    expose:
      - 3000

  backend:
    image: ${DOCKER_USERNAME}/dong-gle-backend
    expose:
      - 8080
    volumes:
      - /home/ubuntu/logs/:/logs/
    environment:
      - SPRING_PROFILES_ACTIVE
      - DB_URL
      - DB_USERNAME
      - DB_PASSWORD

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
      - /home/ubuntu/certs/:/etc/nginx/certs/
      - ./conf-${PROFILE}/:/etc/nginx/conf.d/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend
