export { ReactComponent as HomeIcon } from './home.svg';
export { ReactComponent as CalendarIcon } from './calendar.svg';
export { ReactComponent as PlusCircleIcon } from './plus-circle.svg';
export { ReactComponent as SearchIcon } from './search.svg';
export { ReactComponent as StatsIcon } from './stats.svg';
export { ReactComponent as CheckSymbol } from './check-symbol.svg';
export { ReactComponent as DeleteIcon } from './delete.svg';
export { ReactComponent as PencilIcon } from './pencil.svg';
export { ReactComponent as WritingIcon } from './writing.svg';
