spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY}
      access-token-expire-length: ${ACCESS_TOKEN_EXPIRE_LENGTH}
      refresh-token-expire-length: ${REFRESH_TOKEN_EXPIRE_LENGTH}
kakao_client_id: ${KAKAO_CLIENT_ID}
kakao_client_secret: ${KAKAO_CLIENT_SECRET}
tistory_client_id: ${TISTORY_CLIENT_ID}
tistory_client_secret: ${TISTORY_CLIENT_SECRET}
notion_client_id: ${NOTION_CLIENT_ID}
notion_client_secret: ${NOTION_CLIENT_SECRET}
