spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:10}
      minimum-idle: ${HIKARI_MIN_IDLE:10}
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 12
        max-page-size: 50
security:
  jwt:
    token:
      secret-key: 'wjdgustmdwjdgustmdwjdgustmdwjdgustmdwjdgustmdwjdgustmdwjdgustmdwjdgustmdwjdgustmdwjdgustmdwjdgustmdwjdgustmdwjdgustmd'
      access-token-expire-length: 60000000
      refresh-token-expire-length: 1200000
kakao_client_id: kakao_client_id
kakao_client_secret: kakao_client_secret
tistory_client_id: tistory_client_id
tistory_client_secret: tistory_client_secret
notion_client_id: notion_client_id
notion_client_secret: notion_client_secret
encrypt_secret_key: encryptsecretkey
encrypt_iv: encryptivparamet

aws:
  s3:
    bucket: bucket
    key: key
uploader:
  image-url: https://image.donggle.blog/

server:
  tomcat:
    threads:
      max: ${TOMCAT_MAX_THREADS:200}
    accept-count: ${TOMCAT_ACCEPT_COUNT:100}
    max-connections: ${TOMCAT_MAX_CONNECTIONS:10000}
