spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
kakao_client_secret: kakao_client_secret
kakao_client_id: kakao_client_secret