spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
kakao_client_secret: ${KAKAO_CLIENT_SECRET}
kakao_client_id: ${KAKAO_CLIENT_ID}
tistory_client_id: ${TISTORY_CLIENT_ID}
tistory_client_secret: ${TISTORY_CLIENT_SECRET}