spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
security:
  jwt:
    token:
      secret-key: 'wjdgustmdwjdgustmdwjdgustmdwjdgustmdwjdgustmdwjdgustmdwjdgustmdwjdgustmdwjdgustmdwjdgustmdwjdgustmdwjdgustmdwjdgustmd'
      access-token-expire-length: 600000
      refresh-token-expire-length: 1200000
kakao_client_id: kakao_client_id
kakao_client_secret: kakao_client_secret
tistory_client_id: tistory_client_id
tistory_client_secret: tistory_client_secret
notion_client_id: notion_client_id
notion_client_secret: notion_client_secret
