name: CICD for Frontend Development

on:
  push:
    branches:
      - develop
    paths:
      - 'frontend/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fe-build:
    runs-on: ubuntu-latest 
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REPO }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile-dev
          push: true
          tags: ${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_USERNAME }}/dong-gle-frontend-dev:latest
    
  deploy:
    runs-on: [self-hosted,dev]
    needs: [fe-build]
    steps:
      - name: change permission
        run: |
            sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work/2023-dong-gle/2023-dong-gle

      - name: Docker compose
        working-directory: /home/ubuntu/actions-runner/_work/2023-dong-gle/2023-dong-gle
        run: |
            sudo docker login https://${{ secrets.DOCKER_REPO }} -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker rm -f $(sudo docker -qa)
            sudo docker compose -f docker-compose.dev.yml pull
            sudo docker compose -f docker-compose.dev.yml up -d
