name: Cypress Tests

on:
  pull_request:
    branches:
      - develop
    paths:
      - frontend/**

defaults:
  run:
    working-directory: ./frontend

jobs:
  cypress-run:
    if: contains(github.event.pull_request.labels.*.name, 'frontend')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create .env.development file
        run: |
          touch .env.development
          echo "BASE_URL=${{secrets.BASE_URL_DEVELOPMENT}}" >> .env.development

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: yarn start
          wait-on: 'http://localhost:3000'
          browser: chrome
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
